version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pets_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
  pet-management:
    image: com.mdotm/pets-management:latest
    ports:
      - "8080:8080"
    #environment: Override application properties with environment variables here if needed

volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge