springdoc.swagger-ui.path=/pet-management-doc

openapi.project-description=Service Used For Managing Pets Information
openapi.project-title=Pet Management
openapi.project-version=1.0.0-SNAPSHOT

spring.liquibase.enabled=true
spring.liquibase.liquibase-schema=public
spring.liquibase.default-schema=pets_management

spring.datasource.url=jdbc:postgresql://localhost:5432/pets_db
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.initializationFailTimeout=60000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.minimumIdle=2
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.read-only=false

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.default_schema=pets_management
